(define (problem blocksworldproblem)
   (:domain simple-blocks)
   (:objects blocka blockb blockc)
   (:init (on blockb table)
   	  (on blocka table)
	  (on blockc blocka)
	  (clear blockb)
	  (clear blockc)
   )
   (:goal (and (clear blocka)
   	       (on blocka blockb)
	       (on blockb blockc)
	       (on blockc table)
	  )
    )
)
